# -*- coding: utf-8 -*-
"""PreguntaLLMS2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Av8YdjDGfTAA1bmK8UB3CKPiQFBH-jxf
"""

import pandas as pd
import numpy as np
import random
def generar_caso_de_uso_generar_ranking_estudiantes():
    n = random.randint(6, 20)

    df = pd.DataFrame({
        'nombre': [f'estudiante_{i}' for i in range(n)],
        'nota': np.random.uniform(-2, 7, n),  # incluye errores
        'grupo': np.random.choice(['A', 'B', 'C'], n)
    })

    input_data = {'df': df.copy(),}

    # ===== OUTPUT ESPERADO =====
    df_clean = df[(df['nota'] >= 0) & (df['nota'] <= 5)].copy()
    df_clean = df_clean.sort_values(['grupo', 'nota'], ascending=[True, False])

    df_clean['ranking'] = df_clean.groupby('grupo').cumcount() + 1

    return input_data, df_clean

# --- Ejemplo de uso ---
if __name__ == "__main__":
    # Generamos un caso
    entrada, salida_esperada = generar_caso_de_uso_generar_ranking_estudiantes()

    print("=== INPUT ===")
    print(entrada)

    print("\n=== OUTPUT ===")
    print(salida_esperada)