# -*- coding: utf-8 -*-
"""problema4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RAIa8JkJ3CaZj6v0gQYi2Xh6ir8sGFk3
"""

from sklearn.cluster import KMeans
import pandas as pd
import numpy as np
import random
def generar_caso_de_uso_segmentar_clientes():
    n = random.randint(15, 60)
    n_features = random.randint(2, 5)
    k_clusters = random.randint(2, 5)

    data = np.random.randn(n, n_features)

    cols = [f'var_{i}' for i in range(n_features)]
    df = pd.DataFrame(data, columns=cols)

    input_data = {
        'df': df.copy(),
        'n_clusters': k_clusters
    }

    # ===== OUTPUT ESPERADO =====
    model = KMeans(n_clusters=k_clusters, random_state=42, n_init=10)
    model.fit(df)

    output = (model.labels_, model.cluster_centers_)

    return input_data, output

# --- Ejemplo de uso ---
if __name__ == "__main__":
    # Generamos un caso
    entrada, salida_esperada = generar_caso_de_uso_segmentar_clientes()

    print("=== INPUT ===")
    print(entrada)

    print("\n=== OUTPUT ===")
    print(salida_esperada)