# -*- coding: utf-8 -*-
"""preguntasLLMS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d5KHCuTMsAaR4k3KkkyFC29XM48l7lGz
"""

import pandas as pd
import numpy as np
import random

def generar_caso_de_uso_calcular_ingresos_validos():
    n = random.randint(5, 15)

    categorias = ['tecnologia', 'hogar', 'ropa']
    productos = [f'producto_{i}' for i in range(n)]

    df = pd.DataFrame({
        'producto': productos,
        'precio': np.random.uniform(-20, 100, n),  # incluye errores
        'cantidad': np.random.randint(-3, 20, n),  # incluye errores
        'categoria': np.random.choice(categorias, n)
    })

    input_data = {'df': df.copy(),}

    # ===== OUTPUT ESPERADO =====
    df_clean = df[(df['precio'] > 0) & (df['cantidad'] > 0)].copy()
    df_clean['ingreso'] = df_clean['precio'] * df_clean['cantidad']

    result = df_clean.groupby('categoria')['ingreso'].sum().reset_index()
    result.columns = ['categoria', 'ingreso_total']

    return input_data, result

# --- Ejemplo de uso ---
if __name__ == "__main__":
    # Generamos un caso
    entrada, salida_esperada = generar_caso_de_uso_calcular_ingresos_validos()

    print("=== INPUT ===")
    print(entrada)

    print("\n=== OUTPUT ===")
    print(salida_esperada)