# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OglNjxDayX8n3lixsFJolPwrEdiERYvQ
"""

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
import random

def generar_caso_de_uso_evaluar_modelo_riesgo():
    n = random.randint(30, 80)
    n_features = random.randint(3, 6)

    X = np.random.randn(n, n_features)
    y = np.random.randint(0, 2, n)

    cols = [f'feature_{i}' for i in range(n_features)]
    df = pd.DataFrame(X, columns=cols)
    df['riesgo'] = y

    input_data = {
        'df': df.copy(),
        'target_col': 'riesgo'
    }

    # ===== OUTPUT ESPERADO =====
    X_data = df.drop(columns=['riesgo'])
    y_data = df['riesgo']

    X_train, X_test, y_train, y_test = train_test_split(
        X_data, y_data, test_size=0.2, random_state=42
    )

    model = LogisticRegression(max_iter=200)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)

    output = (acc, model.coef_)

    return input_data, output

# --- Ejemplo de uso ---
if __name__ == "__main__":
    # Generamos un caso
    entrada, salida_esperada = generar_caso_de_uso_evaluar_modelo_riesgo()

    print("=== INPUT ===")
    print(entrada)

    print("\n=== OUTPUT ===")
    print(salida_esperada)